server:
  port: ${TDG_HOST_PORT}
  servlet:
    contextPath: /
    
springfox:
  documentation:
    open-api:
      v3:
        path: /api-docs
  
spring:
  logging:
    level.root: INFO
  data:
    mongodb:
      uri: ${TDG_DB_URI}
      database: ${TDG_DB_NAME}
  jackson:
    date-format: com.catenax.tdm.RFC3339DateFormat
    serialization:      write-dates-as-timestamps: false
  main:
    allow-circular-references: true
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s



