apiVersion: v2
name: testdatagenerator
description: A Helm chart for the Catena-X TestDataGenerator

type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mongodb
    condition: mongodb.enabled
    version: "11.1.10"
    repository: "https://charts.bitnami.com/bitnami"
  - name: keycloak
    condition: iam.enabled
    version: "7.1.17"
    repository: "https://charts.bitnami.com/bitnami"
