iam:
  url: "https://localhost:9001/auth"
  realm: master
  client: tdg-ui
  secret: <your-secret-here>
  local: false

ingress:
  hostname: localhost

backend:
  image: ghcr.io/catenax-ng/product-test-data-generator/tdg:main
  endpoint: /api
  apikey: SPEEDBOAT

frontend:
  image: ghcr.io/catenax-ng/product-test-data-generator/tdg-admin-ui:main

mongodb:
  enabled: true
  hostname: localhost
  database: tdg
  architecture: standalone
  fullnameOverride: db-product-test-data-generator
  global:
    namespaceOverride: product-test-data-generator
  auth:
    usernames: 
      - admin
    passwords: 
      - admin
    databases:
      - tdg

