iam:
  enabled: true
  url: "https://centralidp.demo.catena-x.net/auth"
  realm: CX-Central
  client: Cl12-CX-TestManager
  secret: <path:test-data-generator/data/iam#secret>
  local: false

ingress:
  hostname: tdg.int.demo.catena-x.net

backend:
  image: ghcr.io/catenax-ng/product-test-data-generator/tdg:main
  endpoint: /api
  apikey: <path:test-data-generator/data/api#key>

frontend:
  image: ghcr.io/catenax-ng/product-test-data-generator/tdg-admin-ui:main

mongodb:
  enabled: true
  hostname: db-product-test-data-generator
  database: tdg
  architecture: standalone
  fullnameOverride: db-product-test-data-generator
  global:
    namespaceOverride: product-test-data-generator
  auth:
    rootUser: admin
    rootPassword: admin
    usernames: 
      - tdg
    passwords: 
      - tdg
    databases:
      - tdg

keycloak:
  enabled: true
  fullnameOverride: iam-product-test-data-generator
  global:
    namespaceOverride: product-test-data-generator
  auth:
    adminUser: test
    adminPassword: test
  tls:
    enabled: false
  service:
    ports:
      http: 9000
      https: 9001
  ingress:
    enabled: true
    hostname: tdg-iam.int.demo.catena-x.net
    path: /
    servicePort: https
    tls: true
    selfSigned: true
  postgresql:
    enabled: true

