iam:
  url: "https://centralidp.demo.catena-x.net/auth"
  realm: CX-Central
  client: Cl12-CX-TestManager
  secret: <path:test-data-generator/data/iam#secret>
  local: false

ingress:
  hostname: tdg.int.demo.catena-x.net

backend:
  image: ghcr.io/catenax-ng/product-test-data-generator/tdg:main
  endpoint: /api
  apikey: SPEEDBOAT

frontend:
  image: ghcr.io/catenax-ng/product-test-data-generator/tdg-admin-ui:main

mongodb:
  enabled: true
  hostname: tdg-db.int.demo.catena-x.io
  architecture: standalone
  global:
    namespaceOverride: product-test-data-generator
  auth:
    rootUser: admin
    rootPassword: admin

