iam:
  url: "https://centralidp.demo.catena-x.net/auth"
  realm: CX-Central
  client: Cl12-CX-TestManager
  secret: <path:test-data-generator/data/iam#secret>
  local: false

ingress:
  hostname: tdg.int.demo.catena-x.net

backend:
  image: ghcr.io/catenax-ng/product-test-data-generator/tdg:main
  endpoint: /api
  apikey: SPEEDBOAT

frontend:
  image: ghcr.io/catenax-ng/product-test-data-generator/tdg-admin-ui:main

mongo:
  enabled: true
  host:
    name: tdg-db.int.demo.catena-x.io
    port: 27017
  database: tdg
  credentials:
    user: <path:test-data-generator/data/mongo#username>
    password: <path:test-data-generator/data/mongo#password>

mongodb:
  architecture: standalone
  global:
    namespaceOverride: product-test-data-generator
  auth:
    rootUser: <path:test-data-generator/data/mongo#username>
    rootPassword: <path:test-data-generator/data/mongo#password>

