apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-dbload-{{ .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
data:
{{ (.Files.Glob "db-template/*.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "db-template/*.json").AsConfig | indent 2 }}