apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "testdatagenerator.fullname" . }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "testdatagenerator.fullname" . }}-tdg-app
  template:
    metadata:
      labels:
        app: {{ template "testdatagenerator.fullname" . }}-tdg-app
    spec:
      containers:
        - name: tdg
          image: {{ .Values.backend.image }}
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: TDG_API_KEY
              value: {{ .Values.backend.api-key }}
            - name: TDG_HOST_SECURE
              value: {{ .Values.backend.host.secure }}
            - name: TDG_HOST_NAME
              value: {{ .Values.backend.host.name }}
            - name: TDG_HOST_PORT
              value: {{ .Values.backend.host.external-port }}
            - name: TDG_DB_HOSTNAME
              value: {{ .Values.mongo.host.name }}
            - name: TDG_DB_PORT
              value: {{ .Values.mogno.host.port }}
            - name: TDG_DB_NAME
              value: {{ .Values.mongo.database }}
            - name: TDG_DB_USERNAME
              value: {{ .Values.mongo.credentials.user }}
            - name: TDG_DB_PASSWORD
              value: {{ .Values.mongo.credentials.password }}
          command: [ "echo", "SUCCESS FROM TDG" ]

              