apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "testdatagenerator.fullname" . }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "testdatagenerator.fullname" . }}-tdg-app
  template:
    metadata:
      labels:
        app: {{ template "testdatagenerator.fullname" . }}-tdg-app
    spec:
      containers:
        - name: tdg-admin-ui
          image: ghcr.io/catenax/testdatagenerator/tdg-admin-ui:main
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: TDG_HOST_SECURE
              value: "true"
            - name: TDG_HOST_NAME
              value: "tdg"
            - name: TDG_HOST_PORT
              value: "443"
            - name: TDG_API_KEY
              value: "SPEEDBOAT"
            - name: TDG_API_SECURE
              value: "false"
            - name: TDG_API_HOST_NAME
              value: "tdg"
            - name: TDG_API_HOST_PORT
              value: "8080"
            - name: TDG_IAM_SERVER_URL
              value: {{ .Values.iam.url }}
            - name: TDG_IAM_RESOURCE
              value: "tdg-ui"
            - name: TDG_IAM_REALM
              value: "master"
          command: [ "echo", "SUCCESS FROM TDG ADMIN UI" ]

              