apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "testdatagenerator.fullname" . }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "testdatagenerator.fullname" . }}-tdg-app
  template:
    metadata:
      labels:
        app: {{ template "testdatagenerator.fullname" . }}-tdg-app
    spec:
      containers:
        - name: tdg-admin-ui
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: TDG_HOST_SECURE
              value: {{ .Values.frontend.host.secure }}
            - name: TDG_HOST_NAME
              value: {{ .Values.frontend.host.name }}
            - name: TDG_HOST_PORT
              value: {{ .Values.backend.host.external-port }}
            - name: TDG_API_KEY
              value: {{ .Values.backend.api-key }}
            - name: TDG_API_SECURE
              value: {{ .Values.backend.host.secure }}
            - name: TDG_API_HOST_NAME
              value: {{ .Values.backend.host.name }}
            - name: TDG_API_HOST_PORT
              value: {{ .Values.backend.host.external-port }}
            - name: TDG_API_ENDPOINT
              value: {{ .Values.backend.host.endpoint }}
            - name: TDG_IAM_SERVER_URL
              value: {{ .Values.iam.url }}
            - name: TDG_IAM_RESOURCE
              value: {{ .Values.iam.client }}
            - name: TDG_IAM_REALM
              value: {{ .Values.iam.realm }}
            - name: TDG_IAM_SECRET
              value: {{ .Values.iam.secret }}
          command: [ "echo", "SUCCESS FROM TDG ADMIN UI" ]

              