apiVersion: apps/v1
kind: Statefulset
metadata:
  name: {{ template "testdatagenerator.fullname" . }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "testdatagenerator.fullname" . }}-tdg-app
  template:
    metadata:
      labels:
        app: {{ template "testdatagenerator.fullname" . }}-tdg-app
    spec:
      containers:
        - name: db
          image: mongo:latest
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - name: http
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_DATABASE
              value: tdg
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          command: [ "echo", "SUCCESS FROM DB" ]
