server:
  port: ${TDG_HOST_PORT}
  servlet:
    contextPath: /
    
springfox:
  documentation:
    open-api:
      v3:
        path: /api-docs

spring:
  logging:
    level.root: INFO
  jackson:
    date-format: com.catenax.tdm.RFC3339DateFormat
    serialization:      write-dates-as-timestamps: false
  mustache:
    check-template-location: false
      
vaadin:
  compatibilityMode: false
  productionMode: true
      
keycloak:
  public-client: false
  confidential-port: 0
  ssl-required: external
  auth-server-url: ${TDG_IAM_SERVER_URL}
  realm: ${TDG_IAM_REALM}
  resource: ${TDG_IAM_RESOURCE}
  credentials:
    secret: ${TDG_IAM_SECRET}
