#
# Copyright (c) 2022 BMW AG (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

#################################################################################################################
# Github Workflow for continuous deployment of the test data generator to non-production environments 
#################################################################################################################
# The following secrets are expected to be set
# AZURE_CREDENTIALS           - JSON object containing all info to login to azure via a Service Principal (SP)
#################################################################################################################
# If you intend to use the test data generator in new branches/workspaces/landscapes, see the comments marked 
# ADAPT HERE TO ADD NEW WORKSPACES

name: TestDataGeneratorUI

on: 
  push:
    paths:
      # This is where the test data generator related sources reside
      - 'tdg-admin-ui/**'
      # this workflow file
      - '.github/workflows/tdg-admin-ui.yml'
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  PROJECT: catenax-ng/product-test-data-generator
  IMAGE_NAME: tdg-admin-ui
  
jobs:
  ########################################
  # First job to determine the environment
  ########################################
  # ADAPT HERE TO ADD NEW WORKSPACES

  environment:
    name: Determine Target Environment
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ steps.setvars.outputs.workspace }}

  #########################################################################################
  # Second job does the deployment of the test data generator to the determined environment
  #########################################################################################
  
  deploy:
    name: Build Test Data Generator
    runs-on: ubuntu-latest
    # rely on the first job
    needs: environment
    # rely on successful detection of the workspace, ignore if empty
    if: ${{needs.environment.outputs.workspace}}
    env:
      WORKSPACE: ${{needs.environment.outputs.workspace}}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'adopt'

      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        working-directory: ./tdg-admin-ui
        run: |
          mvn clean package -DskipTests

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          context: ./tdg-admin-ui
          images: ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: tdg/src/main/docker/Dockerfile
          context: ./tdg-admin-ui
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
 
